engines:
  eslint:
    enabled: true
  csslint:
    enabled: true
  nodesecurity:
    enabled: true
  fixme:
    enabled: true
ratings:
  paths:
    - "**.js"
    - "**.es6"
    - "**.html"
    - "**.css"
exclude_paths:
  - "public/javascripts/**"
